Import all the required libraries

In [1]:
import numpy as np
import pandas as pd

Create the nominal and ordinal type of data

In [2]:
np.random.seed(0)
genders = ['male', 'female'] # nominal data
education_level = ['PhD', 'M.Tech', 'B.Tech', '12th'] # ordinal data

num_samples = 1000
gender_data = np.random.choice(genders, size=num_samples)
education_data = np.random.choice(education_level, size=num_samples)

types_of_data_df = pd.DataFrame({
    'Nominal Data': gender_data,
    'Ordinal Data': education_data
})

types_of_data_df

    Nominal Data Ordinal Data
0           male         12th
1         female       B.Tech
2         female         12th
3           male          PhD
4         female          PhD
..           ...          ...
995         male       M.Tech
996         male       B.Tech
997         male       M.Tech
998       female       M.Tech
999         male       M.Tech

[1000 rows x 2 columns]

Create the interval and ratio data

In [3]:
temp_data = np.random.randint(0, 100, size=num_samples) # tenperature
income_data = np.random.randn(num_samples) # income

# Ensure that all the income data values should be ideally positive (1000$)
income_data_positive = income_data - income_data.min() + 1

types_of_data_df['Interval Data'] = temp_data
types_of_data_df['Ratio Data'] = income_data_positive

types_of_data_df

    Nominal Data Ordinal Data  Interval Data  Ratio Data
0           male         12th             81    5.499561
1         female       B.Tech             29    3.972621
2         female         12th             70    3.304911
3           male          PhD             28    5.853978
4         female          PhD             74    4.748325
..           ...          ...            ...         ...
995         male       M.Tech             14    3.902219
996         male       B.Tech             36    3.453359
997         male       M.Tech              4    5.511556
998       female       M.Tech             47    5.241411
999         male       M.Tech              0    4.057327

[1000 rows x 4 columns]

Create the discrete and the continous data

In [4]:
num_of_children_data = np.random.randint(0, 10, size=num_samples)
weight_data = np.random.rand(num_samples) * 10

types_of_data_df['Discrete Data'] = num_of_children_data
types_of_data_df['Continous Data'] = weight_data

types_of_data_df

,Nominal Data,Ordinal Data,Interval Data,Ratio Data,Discrete Data,Continous Data
0,male,12th,81,5.499561,8,0.486673
1,female,B.Tech,29,3.972621,5,7.758212
2,female,12th,70,3.304911,6,0.349534
3,male,PhD,28,5.853978,1,6.547180
4,female,PhD,74,4.748325,4,0.957082
...,...,...,...,...,...,...
995,male,M.Tech,14,3.902219,1,2.617839
996,male,B.Tech,36,3.453359,6,8.388175
997,male,M.Tech,4,5.511556,0,2.790043
998,female,M.Tech,47,5.241411,8,4.808495
999,male,M.Tech,0,4.057327,8,7.842866