**Import all the required libraries**

In [1]:
import pandas as pd
import numpy as np

**Load the data**

In [4]:
dataframe = pd.read_csv('/content/drive/MyDrive/UDEMY Course Recordings/Statistics Module/Sampling Techniques /Population_Survey_Data.csv')
dataframe.head()

   ID  Age Gender  Income  Education Region
0   1   62  Other   96138    Masters   East
1   2   65  Other   76543        PhD   East
2   3   71   Male  138887  Bachelors   East
3   4   18  Other  121643  Bachelors  South
4   5   21   Male  143192    Masters   East

In [5]:
dataframe.shape

(1000, 6)

**1. Random Sampling**

In [6]:
# sample of size = 100 from the 1000 records in the population data
random_sample = dataframe.sample(n = 100, random_state=1)
print(random_sample.head())

      ID  Age  Gender  Income    Education Region
507  508   27   Other  133992  High School   East
818  819   53  Female   92204      Masters  North
452  453   53    Male  138626  High School   West
368  369   47   Other   50745    Bachelors  North
242  243   54  Female   25479    Bachelors  South

In [7]:
random_sample.shape

(100, 6)

**2. Stratified Sampling**

In [8]:
stratified_sampling = dataframe.groupby('Region', group_keys=False).apply(lambda x : x.sample(min(len(x), 25)))

stratified_sampling.to_csv('stratified_sampling.csv')

/tmp/ipython-input-914251646.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_sampling = dataframe.groupby('Region', group_keys=False).apply(lambda x : x.sample(min(len(x), 25)))

In [9]:
stratified_sampling

      ID  Age  Gender  Income    Education Region
695  696   35  Female  149285  High School   East
937  938   46  Female  149071    Bachelors   East
745  746   56  Female  140457          PhD   East
412  413   34   Other   41277          PhD   East
645  646   45    Male   56884    Bachelors   East
..   ...  ...     ...     ...          ...    ...
625  626   46   Other  100840  High School   West
647  648   21  Female   58670      Masters   West
188  189   78    Male  133698  High School   West
41    42   42    Male  107471  High School   West
724  725   69  Female   93499          PhD   West

[100 rows x 6 columns]

In [12]:
dataframe_manufacturing = pd.read_csv('/content/drive/MyDrive/UDEMY Course Recordings/Statistics Module/Sampling Techniques /Manufacturing_Data.csv')
dataframe_manufacturing.head()

   ProductID  BatchNumber ProductionDate  Defective      Weight     Length
0          1           25     2024-01-09          0  462.453744  17.613212
1          2           45     2024-04-18          0  521.766704  15.899234
2          3           20     2024-04-11          0  498.369030  14.177899
3          4           31     2024-06-27          0  488.938762  16.498599
4          5           14     2023-10-27          0  524.459295  15.422276

**3. Cluster Sampling**

In [13]:
clusters = dataframe_manufacturing['BatchNumber'].unique()
clusters

array([25, 45, 20, 31, 14,  8, 36, 30, 21,  9, 11, 42, 35, 47, 12, 22,  5,
       48, 23,  7, 44, 33, 38,  4, 18,  6, 28,  2, 34, 41, 40, 19, 16, 46,
       49, 43, 17,  3, 13, 10, 29, 32, 24, 26, 39, 15,  1, 27, 37])

In [14]:
selected_clusters = np.random.choice(clusters, size=5, replace=False)
selected_clusters

array([46, 40, 44, 45, 20])

In [15]:
clustered_samples = dataframe_manufacturing[dataframe_manufacturing['BatchNumber'].isin(selected_clusters)]
clustered_samples

     ProductID  BatchNumber ProductionDate  Defective      Weight     Length
1            2           45     2024-04-18          0  521.766704  15.899234
2            3           20     2024-04-11          0  498.369030  14.177899
6            7           20     2023-12-19          0  511.999735  13.969603
24          25           20     2023-10-30          0  504.724510  16.143504
25          26           44     2024-05-19          0  484.948354  14.908249
..         ...          ...            ...        ...         ...        ...
974        975           44     2023-12-29          0  530.706871  14.325387
980        981           40     2024-03-18          0  493.152639  16.151341
981        982           20     2023-12-07          0  493.793915  16.102068
990        991           45     2023-09-17          0  513.129274  13.467469
995        996           44     2023-08-14          0  471.355934  11.495162

[95 rows x 6 columns]

In [16]:
clustered_samples.to_csv('clustered_samples.csv')

**4. Systematic Sampling**

In [17]:
systematic_sampling = dataframe.iloc[::10, :]
systematic_sampling

      ID  Age  Gender  Income    Education Region
0      1   62   Other   96138      Masters   East
10    11   39    Male   25241      Masters   West
20    21   56   Other  121272          PhD  South
30    31   27  Female   58115  High School   East
40    41   53  Female  147482    Bachelors  North
..   ...  ...     ...     ...          ...    ...
950  951   78    Male  121159          PhD  North
960  961   55  Female   34823    Bachelors  South
970  971   36   Other  108570    Bachelors  South
980  981   77  Female  123554    Bachelors  North
990  991   28  Female  139725      Masters  North

[100 rows x 6 columns]

In [18]:
dataframe.head()

   ID  Age Gender  Income  Education Region
0   1   62  Other   96138    Masters   East
1   2   65  Other   76543        PhD   East
2   3   71   Male  138887  Bachelors   East
3   4   18  Other  121643  Bachelors  South
4   5   21   Male  143192    Masters   East

**For the entire population, let's try to compute the measures of central tendency: Mean, Median and Mode**

In [19]:
mean_income = dataframe['Income'].mean()
median_income = dataframe['Income'].median()

print(f"Mean Income: {mean_income}")
print(f"Median Income: {median_income}")

Mean Income: 85147.959
Median Income: 85589.5

In [21]:
mode_income = dataframe['Income'].mode()[0]

print(f"Mode Income: {mode_income}")

Mode Income: 52869

Task: **Random Sampling, Stratified Sampling, Cluster Sampling, Systematic Sampling**

Try to find the mean, median and mode of all the above types of sampling and once you evaluate them, check which sampling type results are very close to the population results.*italicised text*